# https://docs.docker.com/compose/reference/
# sudo docker compose --file docker-compose.yml up -d
# Update to the latest image:
# sudo docker compose pull && sudo docker compose up -d
version: '3.1'

services:

  db:
    image: postgres:13
    volumes:
      # Will persist container's /var/lib/postgresql/data folder to host's ./plan/db/ folder
      - "./plan/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: rosario
      POSTGRES_PASSWORD: rosariopwd
      POSTGRES_DB: rosariosis

  web:
    image: rosariosis/rosariosis:master
    #build: .
    ports:
      # host:container
      - "80:80"
    # Warning: if you use a different port (ie. 8080) for host & access from http://localhost:8080
    # wkhtmltopdf will fail with network error: ConnectionRefusedError
    # To fix that, you can use this hack
    # https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach#answer-38753971
    #extra_hosts:
      # Add `127.0.0.1 rosariosisdocker.local` to your /etc/hosts file
      # Then, access from http://rosariosisdocker.local:8080
      # - "rosariosisdocker.local:$DOCKERHOST"
    depends_on:
      - db
    volumes:
      # Will persist container's /var/www/html folder to host's ./plan/rosariosis/ folder
      - "./plan/rosariosis:/var/www/html"
    environment:
      PGHOST: db
      PGUSER: rosario
      PGPASSWORD: rosariopwd
      PGDATABASE: rosariosis
      ROSARIOSIS_YEAR: 2024
#      ROSARIOSIS_LANG: 'es_ES'
